[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.bcmath",
  "php82Extensions.intl",
  "php82Extensions.pdo_mysql"
]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
